apiVersion: v1
kind: Pod
metadata:
  labels:
    role: {{ .Release.Name }}
  name: {{ include "kube-enforcer.fullname" . }}
spec:
  serviceAccountName: {{ .Release.Name }}-sa
  containers:
  - name: kube-enforcer
    image: "{{ .Values.imageCredentials.repositoryUriPrefix }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: Always
    ports:
    - containerPort: 8000
    env:
    - name: AQUA_SERVER_URL
      value: {{ .Values.aqua_server_url }}
    - name: USERNAME
      value: {{ .Values.aqua_username }}
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: {{ .Release.Name }}-aqua-password
          key: admin-password
    - name: AQUA_ENABLE_CACHE
      value: "{{ .Values.aqua_enable_cache }}"
    - name: AQUA_CACHE_EXPIRATION_PERIOD
      value: "{{ .Values.aqua_cache_expiration_period }}"
    {{- if .Values.config_tls_auth }}
    - name: APISERVER_CLIENT_CA_CERT
      valueFrom:
        secretKeyRef:
          name: {{ .Values.config_tls_secret_name }}
          key: {{ .Values.config_tls_secret_key }}
    {{- end }}