apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aquaSecret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ template "username" . }}            # place server username
  password: {{ template "password" . }}            # place server password
  token:    {{ template "token" . }}               # aqua kube enforcer token