{{- if .Values.aqua_password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aqua-password
  labels:
    app: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  admin-password: {{ .Values.aqua_password | b64enc | quote }}
{{- end }}