apiVersion: v1
kind: Service
metadata:
  labels:
    role: {{ .Release.Name }}-role
  name: {{ .Release.Name }}-svc
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    role: {{ .Release.Name }}