# Specifies the secret data for imagePullSecrets needed to fetch the private docker images
imageCredentials:
  create: true
  name: aqua-registry-secret # example
  repositoryUriPrefix: "registry.aquasec.com" # for dockerhub - "docker.io"
  registry: "registry.aquasec.com" #REQUIRED only if create is true, for dockerhub - "index.docker.io/v1/"
  username: ""
  password: ""
  email: "example@gmail.com"

managed: false
environment: aws # aws, acs, onprem
k8s_api_server_manifest_file_path: /etc/kubernetes/manifests/kube-apiserver.yaml

aqua_server_url: https://server_ip:8080
aqua_username: administrator
aqua_password: change
aqua_enable_cache: yes
aqua_cache_expiration_period: 60

config_tls_auth: false
config_tls_secret_name: apiserver-creds 
config_tls_secret_key: ca.pem

image:
  repository: kube-enforcer
  tag: 4.0
  pullPolicy: Always

nameOverride: "kube-enforcer"
fullnameOverride: "kube-enforcer"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi